let selectedDay=0,activeView="today",map=null,mapLayer=null,routeLine=null,mapMarkers=[],demoMode=localStorage.getItem("travelDemo")==="1";
const $=id=>document.getElementById(id);
const fmtDate=s=>s.slice(5).replace("-","/");
const dayIndexByToday=()=>{const p=new Intl.DateTimeFormat("en-CA",{timeZone:"Atlantic/Reykjavik",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date());return TRIP.days.findIndex(d=>d.date===p)};
const referenceDate=()=>demoMode?"2026-11-23":new Intl.DateTimeFormat("en-CA",{timeZone:"Atlantic/Reykjavik",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date());
function relLabel(date){const a=new Date(referenceDate()+"T00:00:00Z"),b=new Date(date+"T00:00:00Z"),n=Math.round((b-a)/864e5);if(referenceDate()<TRIP.days[0].date)return"行程";if(n===0)return"今日";if(n===1)return"明日";if(n===2)return"後日";if(n===-1)return"昨日";return fmtDate(date)}
function icon(name){const p={today:'<circle cx="12" cy="12" r="8"/><path d="M12 8v4l3 2"/>',map:'<path d="m3 6 5-2 8 3 5-2v13l-5 2-8-3-5 2z"/><path d="M8 4v13M16 7v13"/>',booking:'<path d="M5 4h14v16H5z"/><path d="M8 8h8M8 12h8M8 16h5"/>',expense:'<circle cx="12" cy="12" r="8"/><path d="M9 10c0-1 1-2 3-2s3 1 3 2-1 2-3 2-3 1-3 2 1 2 3 2 3-1 3-2M12 6v12"/>',more:'<circle cx="5" cy="12" r="1"/><circle cx="12" cy="12" r="1"/><circle cx="19" cy="12" r="1"/>'}[name]||'';return '<svg viewBox="0 0 24 24">'+p+'</svg>'}
function weatherIcon(code){if(code===0)return'<svg viewBox="0 0 24 24"><circle cx="12" cy="12" r="4"/><path d="M12 2v3M12 19v3M2 12h3M19 12h3M5 5l2 2M17 17l2 2M19 5l-2 2M7 17l-2 2"/></svg>';if([71,73,75,77,85,86].includes(code))return'<svg viewBox="0 0 24 24"><path d="M6 15a4 4 0 0 1 1-7.8A6 6 0 0 1 18 9a3 3 0 0 1 0 6H6z"/><path d="m8 18 1 2m3-2 1 2m3-2 1 2"/></svg>';if(code>=51)return'<svg viewBox="0 0 24 24"><path d="M6 15a4 4 0 0 1 1-7.8A6 6 0 0 1 18 9a3 3 0 0 1 0 6H6z"/><path d="m9 18-1 2m5-2-1 2m5-2-1 2"/></svg>';return'<svg viewBox="0 0 24 24"><path d="M6 16a4 4 0 0 1 1-7.8A6 6 0 0 1 18 10a3 3 0 0 1 0 6H6z"/></svg>'}
const heroImages=[
"https://images.unsplash.com/photo-1504829857797-ddff29c27927?auto=format&fit=crop&w=1400&q=80",
"https://images.unsplash.com/photo-1500042600524-37ecb686c775?auto=format&fit=crop&w=1400&q=80",
"https://images.unsplash.com/photo-1520769669658-f07657f5a307?auto=format&fit=crop&w=1400&q=80",
"https://images.unsplash.com/photo-1516496636080-14fb876e029d?auto=format&fit=crop&w=1400&q=80",
"https://images.unsplash.com/photo-1529963183134-61a90db47eaf?auto=format&fit=crop&w=1400&q=80"
];
function initIcons(){document.querySelectorAll("[data-icon]").forEach(x=>x.innerHTML=icon(x.dataset.icon))}
function renderDayStrip(){const el=$("dayStrip");el.innerHTML=TRIP.days.map((d,i)=>'<button class="day-btn '+(i===selectedDay?'active':'')+'" data-day="'+i+'"><strong>'+d.label+'</strong><small>'+fmtDate(d.date)+'</small></button>').join("");el.querySelectorAll("button").forEach(b=>b.onclick=()=>{selectedDay=+b.dataset.day;renderAll()})}
function renderHero(){const d=TRIP.days[selectedDay];$("heroDay").textContent=d.label+" · "+fmtDate(d.date);$("heroRelativeLabel").textContent=relLabel(d.date);$("heroTitle").textContent=d.name;$("todayKm").textContent=d.km+" km";$("todayDrive").textContent=d.drive;$("todaySunrise").textContent="--:--";$("todaySunset").textContent="--:--";$("heroCard").style.backgroundImage='url("'+heroImages[selectedDay%heroImages.length]+'")';$("heroDemoBadge").hidden=!demoMode;$("timelineHeading").textContent=relLabel(d.date)+"行程";refreshWeather(d)}
function renderTimeline(){const d=TRIP.days[selectedDay],el=$("timeline");el.innerHTML=d.events.map(e=>{const nav=e.lat?'<a class="nav-link" target="_blank" rel="noopener" href="https://www.google.com/maps/dir/?api=1&destination='+e.lat+','+e.lng+'">導航 →</a>':'';return'<div class="timeline-item"><div class="timeline-dot"></div><article class="timeline-card"><div class="timeline-top"><div><div class="type">'+e.type.toUpperCase()+'</div><h3>'+e.title+'</h3></div><div class="time">'+e.time+'</div></div><div class="sub">'+(e.subtitle||'')+'</div><div class="note">'+(e.note||'')+'</div>'+nav+'</article></div>'}).join("")}
function renderStay(){const e=[...TRIP.days[selectedDay].events].reverse().find(x=>x.type==="stay");$("tonightCard").innerHTML=e?'<div class="stay-card"><span class="section-kicker">CHECK-IN</span><h3>'+e.title+'</h3><p>'+e.subtitle+'</p><p>'+e.note+'</p></div>':'<div class="stay-card"><p>今天沒有住宿資料。</p></div>'}
function bookingRender(){const list=TRIP.bookings||[];$("bookingFilters").innerHTML=["全部","住宿","航班","租車","Tour"].map((x,i)=>'<button class="'+(i===0?'active':'')+'">'+x+'</button>').join("");$("bookingList").innerHTML=list.length?list.map(b=>'<div class="booking-card"><span class="section-kicker">'+(b.type||"BOOKING")+'</span><h3>'+b.title+'</h3><p>'+((b.meta||b.dates)||"")+'</p></div>').join(""):'<div class="booking-empty"><strong>私人預訂資料尚未同步</strong><p>登入與 Trusted Device 已完成；Booking No.、PIN、費用等不會放在公開 GitHub bundle。</p></div>'}
async function refreshWeather(d){$("weatherTemp").textContent="--°";$("weatherLabel").textContent="讀取中";$("weatherIconWrap").innerHTML=weatherIcon(3);const p=d.events.find(e=>e.lat);if(!p)return;try{if(demoMode){$("weatherTemp").textContent=["2°","0°","-2°","-3°","-1°","1°","0°","2°"][selectedDay];$("weatherLabel").textContent=["陰天","多雲","雪","陰天","雪","多雲","雨","多雲"][selectedDay];$("weatherIconWrap").innerHTML=weatherIcon(selectedDay===2||selectedDay===4?71:3);$("todaySunrise").textContent=["10:02","10:00","09:59","10:01","10:03","10:05","10:07","10:09"][selectedDay];$("todaySunset").textContent=["15:57","15:52","15:49","15:46","15:43","15:40","15:38","15:35"][selectedDay];return}const u="https://api.open-meteo.com/v1/forecast?latitude="+p.lat+"&longitude="+p.lng+"&daily=weather_code,temperature_2m_max,temperature_2m_min,sunrise,sunset&timezone=Atlantic%2FReykjavik&forecast_days=16";const j=await fetch(u).then(r=>r.json()),i=j.daily?.time?.indexOf(d.date);if(i<0){$("weatherLabel").textContent="待預報";return}$("weatherTemp").textContent=Math.round(j.daily.temperature_2m_max[i])+"°";$("weatherLabel").textContent="預報";$("weatherIconWrap").innerHTML=weatherIcon(j.daily.weather_code[i]);$("todaySunrise").textContent=j.daily.sunrise[i].slice(-5);$("todaySunset").textContent=j.daily.sunset[i].slice(-5)}catch(e){$("weatherLabel").textContent="暫無資料"}}
function switchView(v){activeView=v;document.querySelectorAll(".view").forEach(x=>x.classList.remove("active"));$(v+"View").classList.add("active");document.querySelectorAll(".nav-item[data-target]").forEach(x=>x.classList.toggle("active",x.dataset.target===v));if(v==="map")setTimeout(renderMap,50);if(v==="booking")bookingRender()}
function renderMapStrip(){const el=$("mapDayStrip");el.innerHTML=TRIP.days.map((d,i)=>'<button class="map-day-btn '+(i===selectedDay?'active':'')+'" data-day="'+i+'"><strong>'+d.label+'</strong><small>'+fmtDate(d.date)+'</small></button>').join("");el.querySelectorAll("button").forEach(b=>b.onclick=()=>{selectedDay=+b.dataset.day;renderAll();renderMap()})}
function renderMap(){const d=TRIP.days[selectedDay];$("mapDayLabel").textContent=d.label;$("mapDayName").textContent=d.name;$("mapRangeSummary").textContent="1 天 · "+d.km+" km";renderMapStrip();if(!window.L)return;if(!map){map=L.map("map",{zoomControl:true}).setView([64.2,-18.8],7);L.maplibreGL({style:"https://tiles.openfreemap.org/styles/liberty"}).addTo(map)}mapMarkers.forEach(m=>m.remove());mapMarkers=[];if(routeLine){routeLine.remove();routeLine=null}const pts=d.events.filter(e=>e.lat&&e.lng).map(e=>[e.lat,e.lng]);d.events.filter(e=>e.lat&&e.lng).forEach((e,i)=>{mapMarkers.push(L.marker([e.lat,e.lng]).addTo(map).bindPopup("<b>"+(i+1)+". "+e.title+"</b><br>"+e.time))});if(pts.length>1){routeLine=L.polyline(pts,{color:"#173c35",weight:5,opacity:.85}).addTo(map);map.fitBounds(routeLine.getBounds(),{padding:[35,35]})}else if(pts.length)map.setView(pts[0],10);$("routeCurrent").textContent=d.events[0]?.title||d.name;$("routeMeta").textContent=d.label+" · "+(d.events[0]?.time||"");$("routeDistance").textContent="0";$("routeTotal").textContent=d.km;$("routeStops").innerHTML=d.events.map(e=>"<span>"+e.time+" "+e.title+"</span>").join("")}
function renderAll(){renderHero();renderDayStrip();renderTimeline();renderStay();renderMapStrip();if(activeView==="booking")bookingRender()}
function openTrip(){ $("tripSheet").classList.add("show");$("sheetBackdrop").classList.add("show")}
function closeTrip(){ $("tripSheet").classList.remove("show");$("sheetBackdrop").classList.remove("show")}
function setupUI(){initIcons();document.querySelectorAll("[data-target]").forEach(b=>b.onclick=()=>switchView(b.dataset.target));document.querySelectorAll("[data-nav]").forEach(b=>b.onclick=()=>switchView(b.dataset.nav));$("tripMenuBtn").onclick=openTrip;$("heroMenuBtn").onclick=openTrip;$("closeSheet").onclick=closeTrip;$("sheetBackdrop").onclick=closeTrip;$("demoModeToggle").onclick=()=>{demoMode=!demoMode;localStorage.setItem("travelDemo",demoMode?"1":"0");$("demoModeToggle").classList.toggle("active",demoMode);$("demoModeState").textContent=demoMode?"開啟":"關閉";if(demoMode)selectedDay=3;renderAll()};$("demoModeToggle").classList.toggle("active",demoMode);$("demoModeState").textContent=demoMode?"開啟":"關閉";$("routeSlider").oninput=e=>$("routeDistance").textContent=Math.round(TRIP.days[selectedDay].km*(+e.target.value/100));let ticking=false;addEventListener("scroll",()=>{if(ticking)return;ticking=true;requestAnimationFrame(()=>{$("heroCard")?.classList.toggle("hero-compact",scrollY>130);ticking=false})});const idx=dayIndexByToday();selectedDay=demoMode?3:(idx>=0?idx:0);renderAll()}
function authPaint(s){const msg=$("authMessage"),foot=$("authFoot"),btn=$("magicLinkBtn");if(!msg)return;btn.disabled=["sending_link","registering_device","loading"].includes(s.state);if(s.state==="loading")msg.textContent="正在檢查登入狀態…";if(s.state==="sending_link")msg.textContent="正在寄送一次性登入連結…";if(s.state==="link_sent"){msg.textContent="登入連結已寄出，請到 Gmail 點一下 Magic Link。";foot.textContent="點開後會回到這個 Travel OS，並把這支裝置註冊成 Trusted Device。"}if(s.state==="signed_out")msg.textContent="私人旅程需要驗證此裝置。第一次登入後，這支手機會被記住。";if(s.state==="registering_device")msg.textContent="登入成功，正在核准這支裝置…";if(s.state==="device_error"){msg.textContent="登入成功，但裝置核准失敗。";foot.textContent="請重新整理；若仍失敗我會檢查 Supabase。"}}
async function boot(){setupUI();if("serviceWorker"in navigator)navigator.serviceWorker.register("./service-worker.js").catch(()=>{});try{const local=await TravelStore.init(TRIP);if(local?.trip){TRIP=local.trip;renderAll()}await TravelSync.init()}catch(e){console.warn("Local DB",e)}TravelAuth.onChange(authPaint);authPaint(TravelAuth.snapshot());$("magicLinkForm").onsubmit=async e=>{e.preventDefault();try{await TravelAuth.sendMagicLink($("authEmail").value.trim())}catch(err){$("authMessage").textContent="寄送失敗："+(err.message||err)}};try{await TravelAuth.init()}catch(e){console.error(e)}}
document.addEventListener("DOMContentLoaded",boot);